version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443" # Map HTTPS port
      - "80:80" # Redirect HTTP to HTTPS
    volumes:
      - ./127.0.0.1-key.pem:/frontend/127.0.0.1-key.pem # Mount SSL certificates
      - ./127.0.0.1.pem:/frontend/127.0.0.1.pem # Mount SSL certificates

    env_file:
      - ./.env
    restart: always
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
