"""Initial migration

Revision ID: 0057fa4dae1c
Revises: 53cf5dfd801e
Create Date: 2025-01-10 12:02:47.001243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0057fa4dae1c'
down_revision: Union[str, None] = '53cf5dfd801e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'male',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('MALE', 'FEMALE', name='gender'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'male',
               existing_type=sa.Enum('MALE', 'FEMALE', name='gender'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
