"""Update table columns

Revision ID: 4a734470526c
Revises: 540307c2caf2
Create Date: 2025-01-04 09:27:30.736809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a734470526c'
down_revision: Union[str, None] = '540307c2caf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airline', 'code')
    # ### end Alembic commands ###
