"""add

Revision ID: 53cf5dfd801e
Revises: a65d18c2d970
Create Date: 2025-01-10 11:43:37.661153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53cf5dfd801e'
down_revision: Union[str, None] = 'a65d18c2d970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('booking_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ticket', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ticket', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('ticket', 'passenger_name')
    op.drop_column('ticket', 'visa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('visa', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('ticket', sa.Column('passenger_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('ticket', 'last_name')
    op.drop_column('ticket', 'first_name')
    op.drop_column('invoice', 'booking_code')
    # ### end Alembic commands ###
