"""Useer

Revision ID: a65d18c2d970
Revises: bc89c76263d3
Create Date: 2025-01-10 08:08:57.544184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a65d18c2d970'
down_revision: Union[str, None] = 'bc89c76263d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', name='usetstatus'), nullable=False))
    op.add_column('user', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('flights_handled', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('revenue_generated', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'revenue_generated')
    op.drop_column('user', 'flights_handled')
    op.drop_column('user', 'department')
    op.drop_column('user', 'id_number')
    op.drop_column('user', 'position')
    op.drop_column('user', 'address')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'status')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
